#!/bin/bash
cd /home/dredknaut/Programming/Bash/CryptIntel/crawlers
./coinScape.sh
./NameScrape.sh
./PriceScrape.sh
./VolScrape.sh
./CapScrape.sh
touch pot VolMatch NameMatch coinData lineMatch CapMatch PriceMatch
rm pot VolMatch NameMatch coinData lineMatch CapMatch PriceMatch
cd ..
./csvGen.sh
php uploadQuery.php

#Run PHP script to LOAD DATA into file

#WANTED: garbage collector 

